# Markdown
markdown: kramdown
kramdown:
  input: GFM

# Site settings
permalink: /:title.html
exclude: [Makefile, README.md, _, CNAME]
sass:
  style: compressed

# Site info
url: "http://help.ticketbase.com"
title: "Ticketbase Help Center"

# Google analytics
analytics:
  hostname: "help.ticketbase.com"
  id: "UA-51634688-1"

# Upstream
ticketbase:
  css: "http://www.ticketbase.com/assets/application-3146c4ea9ec2ced9acea6479c7bbbf9b.css"
  typekit: "drm5fgp"

# Default variables
defaults:
  - scope:
      path: ""
    values:
      layout: "article"
      tags: []
  - scope:
      path: "categories"
    values:
      layout: "category"
      tags: []
